# From : https://gist.github.com/mathieucarbou/886d2a6f5c0b51bb261d6a1329beb08d
# Configuration file for an ESP module connected to two separate Linky power meters (smart power meter deployed in France)
# This file is used by esphome tool to build the firmware of the module

esphome:
  name: esp32-linky

# slow pwm definition used for LED blinking  
#   on_boot:
#     priority: -100
#     then:
#       - output.turn_on:
#           my_slow_pwm  
#       - output.set_level:
#           id: my_slow_pwm
#           level: "50%"

# board definition
# https://esphome.io/components/esp8266.html
# esp8266:
#   board: d1_mini

# https://esphome.io/components/esp32.html
esp32:
  # board: esp32doit-devkit-v1
  # variant: esp32

  # M.G.
  board: esp32dev
  framework:
    type: esp-idf

# For blinking the internal green LED on D2
# output:
#     platform: slow_pwm
#     pin: GPIO2
#     id: my_slow_pwm
#     period: 1000ms

# WiFi Component: https://esphome.io/components/wifi.html
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # manual_ip:
  #   static_ip: 192.168.125.84
  #   gateway: 192.168.0.254
  #   subnet: 255.255.255.0
  #    dns1: 192.168.125.1
  ap:
    ssid: "Esp32-Test Fallback Hotspot"
    password: "7YFRVWvdJckX"

# OTA Update Component: https://esphome.io/components/ota.html
ota:
 - platform: esphome
   password: "ec2d4ff615e36a8b961615aac8e5678d"

# Logger Component: https://esphome.io/components/logger.html
logger:

# Native API Component: https://esphome.io/components/api.html
api:
  encryption:
   # key: "QkX9xy8E0SiTICKmMut1oTkaM085qt2uUenpqdmqcXM="
   key: !secret api_key

# Captive Portal: https://esphome.io/components/captive_portal.html
captive_portal:

# Web Server: https://esphome.io/components/web_server.html
web_server:
  port: 80

# Time: https://esphome.io/components/time.html
time:
  - platform: homeassistant
    timezone: "Europe/Paris"
    id: homeassistant_time

# Status Binary Sensor: https://esphome.io/components/binary_sensor/status.html
binary_sensor:
   # statut
     - platform: status
       name: "Statut"

# Restart Button: https://esphome.io/components/button/restart.html
button:
  - platform: restart
    name: "Linky Restart"

packages:
  linky1: !include
    #file: common/linky/linky_TIC_historic_base_mono.yaml    # uncomment this line if the counter is in historic base mono mode
    file: common/linky/linky_TIC_historic_hphc_mono.yaml     # uncomment this line if the counter is in historic hphc mono mode
    # file: common/linky/linky_TIC_standard_base_mono.yaml   # uncomment this line if the counter is in standard base mono mode
    vars:
      bus_id: bus1
      uart_pin: GPIO16
      # use default UART2
      update_interval: 15s

  # M.G. un seul linky : link2 mis en commentaire
  # linky2: !include
  #   #file: common/linky/linky_TIC_historic_base_mono.yaml    # uncomment this line if the counter is in historic base mono mode
  #   file: common/linky/linky_TIC_historic_hphc_mono.yaml     # uncomment this line if the counter is in historic hphc mono mode
  #   # file: common/linky/linky_TIC_standard_base_mono.yaml   # uncomment this line if the counter is in standard base mono mode
  #   vars:
  #     bus_id: bus2
  #     uart_pin: GPIO35  # this is a GPIO input pin only to avoid any risk of conflict
  #     update_interval: 15s

# https://esphome.io/components/sensor/index.html
sensor:
  # WiFi
  - platform: wifi_signal
    name: "Linky WiFi Signal"
    unit_of_measurement: dB
    device_class: signal_strength
    accuracy_decimals: 0
    update_interval: 60s
  # Uptime
  - platform: uptime
    name: "Linky Uptime"
    unit_of_measurement: s
    device_class: duration
    accuracy_decimals: 0
    update_interval: 60s
  
# https://esphome.io/components/text_sensor/index.html
text_sensor:
  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true
  - platform: wifi_info
    ip_address:
      name: Linky IP Address
    mac_address:
      name: Linky Wifi Mac Address
    ssid:
      name: Linky Wifi SSID
    bssid:
      name: Linky Wifi BSSID
